# Generated by Django 4.0.5 on 2022-06-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField(blank=True)),
                ('reference', models.TextField(blank=True, max_length=5000)),
            ],
        ),
    ]
